package com.example.localchat.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class WebConfig implements WebMvcConfigurer {

    // ⚠️ Please modify this to the "Absolute Path" of the outputs folder generated by your Python script.
    // Note: Must end with a trailing slash "/" and start with the "file:" prefix.
    private static final String OUTPUT_DIR = "file:D:/ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/api/outputs/";

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        // Map the URL pattern /images/** to the physical directory on the hard drive
        registry.addResourceHandler("/images/**")
                .addResourceLocations(OUTPUT_DIR);
    }
}